//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtlobPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminview
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string RestaurantName { get; set; }
        public string ItemName { get; set; }
        public double ItemPrice { get; set; }
        public double OrderPrice { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
