//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtlobPlus
{
    using System;
    
    public partial class getOrderByUserID_Result1
    {
        public int UserID { get; set; }
        public int OrderID { get; set; }
        public string RestaurantName { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreationDate { get; set; }
        public double OrderPrice { get; set; }
        public double Fees { get; set; }
    }
}
