//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtlobPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderID { get; set; }
        public int RestaurantID { get; set; }
        public int UserID { get; set; }
        public double OrderPrice { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> adminID { get; set; }
        public double Fees { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OStatu OStatu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
